dist: xenial
language: python
cache:
  pip: true
before_script:
  - pip install --upgrade tox setuptools virtualenv pytest
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-pytest
    - python: 3.4
      env: TOXENV=py34-pytest
    - python: 3.5
      env: TOXENV=py35-pytest
    - python: 3.6
      env: TOXENV=py36-pytest
    - python: 3.7
      env: TOXENV=py37-pytest
    - python: pypy
      env: TOXENV=pypy-pytest
    - python: 3.7
      env: TOXENV=py37-flake8
    - python: 3.7
      env: TOXENV=py37-pylint
    - python: 3.7
      env: TOXENV=py37-pre
    - python: 3.7
      env: TOXENV=py37-flake8
    - python: 3.7
      env: TOXENV=py37-pylint
    - python: 3.7
      env: TOXENV=py37-pre
    - env: TEST=coverage
      os: linux
      python: 3.6
install:
  - pip install --upgrade pip || pip3 install --upgrade pip
  - pip install git+https://github.com/lukasz-migas/SimpleParam.git
  - if [ "${TEST}" == "coverage" ]; then pip install codecov pytest==3.6 pytest-cov
    pytest-sugar pytest-travis-fold; fi;
script:
  - SRC_DIR=$(pwd)
  - echo $SRC_DIR
  - ls || dir
  - if [[ "${TEST}" == "coverage" ]]; then py.test --cov; else tox; fi;
notifications:
  email: false
after_success:
  - if [ "${TEST}" == "coverage" ]; then codecov --token=38b70ce4-9b10-4aee-b422-fe9e92cc2978;
    fi

deploy:
  branch: master
  provider: pypi
  user: "__token__"
  password:
    secure: WYpBY9Z7M2FQk6/8zUf+sS8W+BKnTI2OG3Rb0nEBOjU4Er9cBS8OurfvBaj4sVgviVL0LE6enAWldJ8gOsNG+jBKOoLW8BHM9CFB68ijih/UGFK/oWmkFTWGeKyfPmLuJkcaHLlCdZYQ4JoK77J/ae1MCheWy6IpV+snDvc9B27NlG4BN/xI6zeTjyN/MxJEOA/wj/VBH2H8UFhpcvxn57dcUgZ9w6J9RtUkql3SroOuzgv5tHd4dqgoO3U3GoEuDvQw6A6DBq9+Y0tiv1c87pr5KyHtRMm+D4IuPyPVuvU3zlk4K6ZHlokkOU+zdebMp5qmzHdhOtwX1DkUJzu2P1/rVwJvhdTaDcB6/mBLIdLDS1Ez5hCu3t1yvz4DIwy7A5LGC64aeI8bmYybjXJKxll1vowYt/SSVM1FjbQrwBqi4d8JKIaQUFKT8b0XpD8oK/XV2lf3feAghcYfl3lgw6ogqjifibECdFWJFMRB54yBsRYsjnJR0qw/xFk7jwzi87xDxAmdhWrLlfvPx/DDm1FY+W2zm8WtIxiHQs0loH144uol9YcHuaHsWWV+ZzCpLWYyk/4DHjJiPEyhmdEpMgLujh1mDoGgkEbcwpwAG4+nUONL8QpvBntG5F4ixYxUac4dX+xIg4y7Cuqu0DOjbcM0qoDs2YhA/U8Wv3/bYmc=
  skip_existing: true
  skip_cleanup: true
